### ISSUE TITLE
Program runs once, crashes when importing mesh and fails to start with Segmantation Fault after that.

### ISSUE THREAD

**Issue by FazTheguyovathere** [armory3d/armortools#2002]
**ArmorPaint version:**

Git aaddba81a42c197a1bad48eb41172c77f9b14b6b

**OS / GPU model:**
Linux Mint 22.2 x86_64
Intel UHD Graphics 630

**Issue description:**
Compiled the git build, program runs fine at first. However, if the starter project is edited, even if the project isn't saved, and I exit the program, it fails to start after that. Running with terminal, the only thing that outputs is "Segmentation Fault" or "Segmentation Fault (Core Dumped)". When I import a mesh the program crashes and same thing happens.

I can reverse this by deleting and replacing the Data folder, essentially reinstalling the program. But the issues remain.

**Steps to reproduce:**

Run ArmorPaint, edit the starter cube, exit, try to run ArmorPaint again.

**Comment by luboslenco** [comment]
Thanks a lot for reporting this. Once you get it to crash and you are no longer able to start it - can you please locate the `ArmorPaint/data/config.json` file and paste it here? It sounds like it somehow gets corrupted, preventing the program from starting properly.

**Comment by FazTheguyovathere** [comment]
Sure thing, though, nothing seems out of the ordinary.

`{"version":"1","sha":"addba81","locale":"en","window_mode":0,"window_w":1440,"window_h":828,"window_x":0,"window_y":0,"window_resizable":true,"window_maximizable":true,"window_minimizable":true,"window_vsync":true,"window_frequency":60,"window_scale":1,000000,"rp_supersample":1,000000,"rp_ssao":false,"rp_bloom":false,"rp_vignette":0,200000,"rp_grain":0,090000,"recent_projects":["/home/user/Documents/blender/test.arm"],"bookmarks":[],"plugins":[],"keymap":"default.json","theme":"default.json","undo_steps":4,"camera_fov":0,690000,"camera_pan_speed":1,000000,"camera_zoom_speed":1,000000,"camera_rotation_speed":1,000000,"camera_upside_down":false,"zoom_direction":0,"wrap_mouse":false,"show_asset_names":false,"touch_ui":false,"splash_screen":false,"layout":[280,414,414,578,369,240,1],"layout_tabs":[0,0,0],"camera_controls":0,"server":"https://armorpaint.fra1.digitaloceanspaces.com","viewport_mode":0,"pathtrace_mode":0,"pressure_radius":true,"pressure_sensitivity":1,000000,"displace_strength":0,000000,"layer_res":4,"brush_live":false,"node_previews":false,"pressure_hardness":true,"pressure_angle":false,"pressure_opacity":false,"material_live":true,"brush_depth_reject":true,"brush_angle_reject":true,"brush_alpha_discard":0,100000,"dilate_radius":2,"blender":"","scene_atlas_res":6,"grid_snap":false,"experimental":false,"neural_backend":1}`

**Comment by FailbotV02** [comment]
I have exactly the same problem. 

Specs:
Linux Mint 22.2 x86_64
Nvidia 3070TI
Ryzen 7 5800x

{"version":"1","sha":"e0d8cf4","locale":"en","window_mode":0,"window_w":1720,"window_h":960,"window_x":0,"window_y":0,"window_resizable":true,"window_maximizable":true,"window_minimizable":true,"window_vsync":true,"window_frequency":143,"window_scale":1,000000,"rp_supersample":1,000000,"rp_ssao":true,"rp_bloom":false,"rp_vignette":0,200000,"rp_grain":0,090000,"recent_projects":[],"bookmarks":[],"plugins":[],"keymap":"default.json","theme":"default.json","undo_steps":4,"camera_fov":0,690000,"camera_pan_speed":1,000000,"camera_zoom_speed":1,000000,"camera_rotation_speed":1,000000,"camera_upside_down":false,"zoom_direction":0,"wrap_mouse":false,"show_asset_names":false,"touch_ui":false,"splash_screen":false,"layout":[280,480,480,723,435,33,1],"layout_tabs":[0,1,0],"camera_controls":0,"server":"https://armorpaint.fra1.digitaloceanspaces.com","viewport_mode":0,"pathtrace_mode":0,"pressure_radius":true,"pressure_sensitivity":1,000000,"displace_strength":0,000000,"layer_res":4,"brush_live":false,"node_previews":false,"pressure_hardness":true,"pressure_angle":false,"pressure_opacity":false,"material_live":true,"brush_depth_reject":true,"brush_angle_reject":true,"brush_alpha_discard":0,100000,"dilate_radius":2,"blender":"","scene_atlas_res":6,"grid_snap":false,"experimental":false,"neural_backend":1}

**Comment by luboslenco** [comment]
It should be resolved in the newly updated `ArmorPaint_10alpha_linux64.zip` and the latest git version (https://github.com/armory3d/armortools/commit/ca22b57c62ff1cd0bce08c53ca7f1ae3b648cba2). Thanks again for the help!

The problem was in json number encoding using a comma instead of period (locale issue).

> "window_scale":1,000000,

should be 

> "window_scale":1.000000,

**Comment by FazTheguyovathere** [comment]
The issue is fixed, partially. While the program is more usable, it crashes when I import a blend file and refuses to start with the same error. Seeing as it opens again normally when I delete the config, it must be a config issue again.

`{"version":"1","sha":"a22b57c","locale":"en","window_mode":0,"window_w":1440,"window_h":828,"window_x":0,"window_y":0,"window_resizable":true,"window_maximizable":true,"window_minimizable":true,"window_vsync":true,"window_frequency":60,"window_scale":1,000000,"rp_supersample":1,000000,"rp_ssao":true,"rp_bloom":false,"rp_vignette":0,200000,"rp_grain":0,090000,"recent_projects":[],"bookmarks":[],"plugins":[],"keymap":"default.json","theme":"default.json","undo_steps":4,"camera_fov":0,690000,"camera_pan_speed":1,000000,"camera_zoom_speed":1,000000,"camera_rotation_speed":1,000000,"camera_upside_down":false,"zoom_direction":0,"wrap_mouse":false,"show_asset_names":false,"touch_ui":false,"splash_screen":false,"layout":[280,414,414,578,369,33,1],"layout_tabs":[0,0,0],"camera_controls":0,"server":"https://armorpaint.fra1.digitaloceanspaces.com","viewport_mode":0,"pathtrace_mode":0,"pressure_radius":true,"pressure_sensitivity":1,000000,"displace_strength":0,000000,"layer_res":4,"brush_live":false,"node_previews":false,"pressure_hardness":true,"pressure_angle":false,"pressure_opacity":false,"material_live":true,"brush_depth_reject":true,"brush_angle_reject":true,"brush_alpha_discard":0,100000,"dilate_radius":2,"blender":"/home/user/software/blender-5.0.0-linux-x64/blender","scene_atlas_res":6,"grid_snap":false,"experimental":false,"neural_backend":1}`

**Comment by FazTheguyovathere** [comment]
Bug still happens after 1603f0ce82b3ff28a7daca80bda33bf753cc89a0

**Comment by FailbotV02** [comment]
same here. i compiled the newest version, and the bug still happens

**Comment by luboslenco** [comment]
Pushed another fix attempt at https://github.com/armory3d/armortools/commit/5567284c9d8b8b8e68c81903851ff60b915746a4 and updated `ArmorPaint_10alpha_linux64.zip` again, thanks for the patience.

**Comment by FazTheguyovathere** [comment]
That should be it! In my testing with 5567284c9d8b8b8e68c81903851ff60b915746a4, the program is much more stable, and functions almost flawlessly. With the only problem I see for now being Blender imports on Linux but I think that should be its own issue.

**Comment by luboslenco** [comment]
Great to hear! Please feel welcome to open more issues, will keep working on it, thanks.
